[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

# Base Sepolia Testnet Configuration
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Gas settings optimized for Base
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing
verbosity = 2